project:
  type: website

website:
  title: "Sana Shaik"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "About Me"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Contact"
        href: contact.qmd
      - text: "Interests"
        href: hobbies.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

 

